### ISSUE TITLE
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe

### ISSUE THREAD

**Issue by 3tty0n** [3tty0n/gatling-thrift#4]
```scala
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:288)
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:887)
	at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:911)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:70)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:155)
	at io.netty.util.ResourceLeakDetector.<init>(ResourceLeakDetector.java:200)
	at io.netty.util.ResourceLeakDetectorFactory$DefaultResourceLeakDetectorFactory.newResourceLeakDetector(ResourceLeakDetectorFactory.java:201)
	at io.netty.util.HashedWheelTimer.<clinit>(HashedWheelTimer.java:89)
	at com.twitter.finagle.netty4.Netty4HashedWheelTimer.<init>(Netty4HashedWheelTimer.scala:100)
	at com.twitter.finagle.netty4.Netty4HashedWheelTimer$.<init>(Netty4HashedWheelTimer.scala:113)
	at com.twitter.finagle.netty4.Netty4HashedWheelTimer$.<clinit>(Netty4HashedWheelTimer.scala)
	at com.twitter.finagle.Thrift$Client$.<init>(Thrift.scala:215)
	at com.twitter.finagle.Thrift$Client$.<clinit>(Thrift.scala)
	at com.twitter.finagle.Thrift$.<init>(Thrift.scala:341)
	at com.twitter.finagle.Thrift$.<clinit>(Thrift.scala)
	at simulation.ThriftSimulationExample.<init>(ThriftSimulationExample.scala:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.gatling.app.Gatling$.io$gatling$app$Gatling$$$anonfun$1(Gatling.scala:41)
	at io.gatling.app.Gatling.run(Gatling.scala:92)
	at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:75)
	at io.gatling.app.Gatling.start(Gatling.scala:65)
	at io.gatling.app.Gatling$.start(Gatling.scala:57)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
	at io.gatling.thrift.testrunner.GatlingRunner$class.main(GatlingRunner.scala:19)
	at simulation.ThriftSimulationMain$.main(ThriftSimulationExample.scala:15)
	at simulation.ThriftSimulationMain.main(ThriftSimulationExample.scala)
```

**Comment by 3tty0n** [comment]
https://github.com/netty/netty/issues/6901
